<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <link rel='stylesheet' href='css/lib/vader/jquery-ui.min.css' />
    <link href='css/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='css/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
    <script src='js/fullcalendar/lib/moment.min.js'></script>
    <script src='js/fullcalendar/lib/jquery.min.js'></script>
    <script src='js/fullcalendar/lib/jquery-ui.custom.min.js'></script>
    <script src='js/fullcalendar/fullcalendar.js'></script>
    <script src='js/fullcalendar/lang/lang-all.js'></script>
    <script src='js/raidplan-calendar.js'></script>

    <script>
        //WLTODO Events aus JSON laden welches aus dem Controller kommt


    </script>
    <style>

        body {
            margin: 0;
            padding: 0;
            font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
            font-size: 14px;
        }

        #calendar {
            width: 1100px;
            margin: 60px auto;
        }

    </style>
</head>
<body>
<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Events';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('addevent');?>">Add new Event</a>
</p>

<table class="table">
    <tr>
        <th>id</th>
        <th>titel</th>
        <th>Beschreibung</th>
        <th>datetime</th>
        <th>status</th>
        <th>activityid</th>
        <th>invited</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($events as $event) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($event->id);?></td>
            <td><?php echo $this->escapeHtml($event->titel);?></td>
            <td><?php echo $this->escapeHtml($event->beschreibung);?></td>
            <td><?php echo $this->escapeHtml($event->datetime);?></td>
            <td><?php echo $this->escapeHtml($event->status);?></td>
            <td><?php echo $this->escapeHtml($event->activityid);?></td>
            <td><?php echo $this->escapeHtml($event->invited);?></td>
            <td>
                <a href="<?php
                echo $this->url('editevent',
                    array('id' => $event->id));?>">Edit</a>
                <a href="<?php echo $this->url('deleteevent',
                    array('id' => $event->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>



<div id='calendar'></div>
<div id='debug'></div>
<?php //WLTODO Kalender onclick, ondrop, onedit callbacks implementieren ?>
</body>
</html>
