<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <link rel='stylesheet' href='css/lib/vader/jquery-ui.min.css' />
    <link href='css/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='css/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
    <script src='js/fullcalendar/lib/moment.min.js'></script>
    <script src='js/fullcalendar/lib/jquery.min.js'></script>
    <script src='js/fullcalendar/lib/jquery-ui.custom.min.js'></script>
    <script src='js/fullcalendar/fullcalendar.js'></script>
    <script src='js/fullcalendar/lang/lang-all.js'></script>
    <script src='js/raidplan-calendar.js'></script>
    <script>
    </script>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
            font-size: 14px;
        }
        #calendar {
            width: 1110px;
            margin: 10px auto;
        }
    </style>
</head>

<body>
<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Events';
$this->headTitle($title);
?>
<br>
<br>
<br>
<div class="panel panel-default">
    <div class="panel-heading">Eventübersicht</div>
    <button id="my-next-button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button"><span class="ui-button-text">Nextbtn</span></button>
    <div class="panel-body">
        <button id="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button"><span class="ui-button-text"><a href="<?php echo $this->url('addevent');?>">Event hinzufügen</a></span></button>
        <div id='calendar'></div>
        <div id='debug'></div>
    </div>
</div>
<?php //WLTODO Kalender ondrop, onedit callbacks implementieren ?>
</body>
</html>
