<?php
//echo "<br>ausgabe:";
//print_r('<pre');
//print_r($_REQUEST);
//print_r('</pre');

$title = 'Edit Event';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$playerChoose = $this->playerChoose;
$form = $this->form;
$form->setAttribute('action', $this->url(
    'editevent',
    array(
        'id'     => $this->id,
    )
));

$form->setAttribute('role', 'form');
$form->setAttribute('style', 'width: 300px;');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('titel'));
echo $this->formRow($form->get('beschreibung'));
echo $this->formRow($form->get('datetime'));
echo $this->formRow($form->get('status'));
echo $this->formRow($form->get('activityid'));
echo $this->formRow($form->get('invited'));
echo $this->formRow($form->get('accepted'));
echo $this->formRow($form->get('declined'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


echo '<br><br>';


//echo $this->playerForm->printData('AddPlayerForm', $this->playerdata);
echo $this->playerForm->printData('PlayerList', $this->playerdata);
//echo '<table>';
//    foreach ($this->playerdata as $playerentry) {
//        echo '<tr>';
//        foreach ($playerentry as $playerfield) {
//            echo '<td>';
//                echo $playerfield;
//            echo '</td>';
//        }
//        echo '</tr>';
//    }
//echo '</table>';



?>