<?php
//echo "<br>ausgabe:";
//print_r('<pre');
//print_r($_REQUEST);
//print_r('</pre');

$title = 'Edit Event';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$playerChoose = $this->playerChoose;
$form = $this->form;
$form->setAttribute('action', $this->url(
    'editevent',
    array(
        'id'     => $this->id,
    )
));

$form->setAttribute('role', 'form');
$form->setAttribute('style', 'width: 300px;');
$form->prepare();



//echo $this->playerForm->printData('AddPlayerForm', $this->playerdata);

//echo '<table>';
//    foreach ($this->playerdata as $playerentry) {
//        echo '<tr>';
//        foreach ($playerentry as $playerfield) {
//            echo '<td>';
//                echo $playerfield;
//            echo '</td>';
//        }
//        echo '</tr>';
//    }
//echo '</table>';



?>

<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Eventdaten</a></li>
        <li><a href="#tabs-2">Teilnehmer</a></li>
    </ul>
    <div id="tabs-1">
        <p>
            <?php


            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('titel'));
            echo $this->formRow($form->get('beschreibung'));
            //echo $this->formRow($form->get('datetime'));
            echo '<label>Datum:</label><input type="text" id="datepicker" class="form-control" value="'.$this->eventData->datetime.'">';
            echo $this->formRow($form->get('status'));
            echo $this->formRow($form->get('activityid'));
            echo $this->formRow($form->get('invited'));
            echo $this->formRow($form->get('accepted'));
            echo $this->formRow($form->get('declined'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();

            ?>
        </p>
    </div>
    <div id="tabs-2">
        <p><?php echo $this->playerForm->printData('PlayerList', $this->playerdata); ?></p>
    </div>
</div>
<script>
    $(document).ready(function() {
        $( "#tabs" ).tabs();
    });
    $(function() {
        $( "#datepicker" ).datepicker();
    });

</script>