<?php

?>


<div class="panel panel-default" id="eventcontainer">
    <div class="panel-heading">Eventdetails</div>
    <?php
        if ($this->isadmin) {
            echo '<button id="loadedit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"><span class="ui-button-text">Event editieren<span></span></button>';
            echo '<button id="deleteevent" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"><span class="ui-button-text">Event löschen<span></span></button>';
        }
    ?>
    <div class="panel-body" >
        <?php echo $this->eventform->getViewEventForm($this->eventsmodel); ?>
    </div>
</div>
