<?php echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/crystalscroll.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/clockpicker.css')
        ->prependStylesheet($this->basePath() . '/css/datepicker.css')
        ->prependStylesheet($this->basePath() . '/css/raidplan.css')
        ->prependStylesheet($this->basePath() . '/css/lib/vader/jquery-ui.min.css')?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        //->prependFile($this->basePath() . '/js/dateformat.js')
        ->prependFile($this->basePath() . '/js/crystalscroll.js')
        ->prependFile($this->basePath() . '/js/ajaxfunctions.js')
        ->prependFile($this->basePath() . '/js/raidplan.js')
        ->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
        ->prependFile($this->basePath() . '/js/clockpicker.js')
        ->prependFile($this->basePath() . '/js/fullcalendar/lib/jquery-ui-1.10.4.custom.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))




    ; ?>

</head>
<body class="layoutbody">
<div id="logoheaderwrap">

    <div id="logoheader">
        <div id="crystals">
            <div class="crystal_01"></div>
            <div class="crystal_02"></div>
            <div class="crystal_03"></div>
        </div>
    </div>
</div>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="mainnavbar" style="margin-top:110px">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Lions Den') ?></a>-->
        </div>
        <div class="collapse navbar-collapse" id="nav">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container" style="margin-top:110px">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <!--<p>&copy; <?php //echo date('Y') ?> by Christian Meissner. <?php //echo $this->translate('All rights reserved.') ?></p>-->
        <p>&copy 2014 by Tyantreides</p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
